name: Publish Docker image
on:
  push:
#    branches:
#      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: "amrfarid/${{ github.event.repository.name }}"
          tags: |
            ${{ github.sha }}
            latest

      - uses: actions/checkout@v3

      - uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max